export interface SeedDefinitionSeedData {
  seedId: string;
  label: string;
  rarity: 'common' | 'rare' | 'legendary';
  sortOrder: number;
  growSeconds: number;
  matureSeconds: number;
  collectWindowSeconds: number;
  baseYieldGold: number;
  strategyNote: string;
  lore: string;
}

const hour = 60 * 60;
const defaultCollectWindowSeconds = 30 * 60;
const longCollectWindowSeconds = 24 * hour;

export const SEED_DEFINITION_SEEDS: SeedDefinitionSeedData[] = [
  {
    seedId: 'qilingya',
    label: '启灵芽',
    rarity: 'common',
    sortOrder: 1,
    growSeconds: 10 + 0,
    matureSeconds: 10,
    collectWindowSeconds: defaultCollectWindowSeconds,
    baseYieldGold: 50,
    strategyNote: '新手教程种，十秒完成第一轮收获，用来串起种田、灵宠和首次掠夺。',
    lore: '只在开荒时授予的一枚灵芽，破土极快，适合新人理解第一轮经营。',
  },
  {
    seedId: 'qinglingmai',
    label: '青灵麦',
    rarity: 'common',
    sortOrder: 10,
    growSeconds: 2 * hour + 1 * hour,
    matureSeconds: 3 * hour,
    collectWindowSeconds: defaultCollectWindowSeconds,
    baseYieldGold: 200,
    strategyNote: '标准稳收基准种，适合新玩家理解成熟和枯萎收益。',
    lore: '田野间最常见的灵粮，穗头泛淡青光泽，脱壳后熬粥清香回甘。',
  },
  {
    seedId: 'xunyamai',
    label: '风云稻',
    rarity: 'common',
    sortOrder: 20,
    growSeconds: 15 * 60 + 15 * 60,
    matureSeconds: 30 * 60,
    collectWindowSeconds: defaultCollectWindowSeconds,
    baseYieldGold: 200,
    strategyNote: '半小时快收种，适合碎片时间上线后迅速完成一轮收益。',
    lore: '稻芒起势极快，晨起沾露便能成势，半个时辰内就能完成一轮收益。',
  },
  {
    seedId: 'ninglucao',
    label: '凝露草',
    rarity: 'common',
    sortOrder: 30,
    growSeconds: 10 * hour,
    matureSeconds: 10 * hour,
    collectWindowSeconds: longCollectWindowSeconds,
    baseYieldGold: 800,
    strategyNote: '长线安睡种，10 小时成熟，24 小时内不枯萎，适合睡前或上班前规划。',
    lore: '叶尖常凝夜露，晨时如泪珠滚落，有清心明目之效。',
  },
  {
    seedId: 'suixinhua',
    label: '碎心花',
    rarity: 'common',
    sortOrder: 40,
    growSeconds: 2 * hour + 1 * hour,
    matureSeconds: 3 * hour,
    collectWindowSeconds: defaultCollectWindowSeconds,
    baseYieldGold: 300,
    strategyNote: '高折损高回报种，高收益波动很强。',
    lore: '花瓣薄如蝉翼，嫣红带紫纹，采摘时指尖会传来短暂刺痛。',
  },
  {
    seedId: 'baiyulian',
    label: '白玉莲',
    rarity: 'common',
    sortOrder: 50,
    growSeconds: 3 * hour + 1.5 * hour,
    matureSeconds: 4.5 * hour,
    collectWindowSeconds: defaultCollectWindowSeconds,
    baseYieldGold: 220,
    strategyNote: '低频保值种，错过窗口也不容易血亏。',
    lore: '纯白无瑕，瓣如凝脂，生于清澈浅塘。',
  },
  {
    seedId: 'yingyuezhu',
    label: '影月竹',
    rarity: 'common',
    sortOrder: 60,
    growSeconds: 2.5 * hour + 1 * hour,
    matureSeconds: 3.5 * hour,
    collectWindowSeconds: defaultCollectWindowSeconds,
    baseYieldGold: 230,
    strategyNote: '稳健中速种，方便不想极端卡点的玩家切换。',
    lore: '竹节映月生辉，夜风吹过时会留下淡淡银影。',
  },
  {
    seedId: 'qianjiteng',
    label: '牵机藤',
    rarity: 'common',
    sortOrder: 70,
    growSeconds: 2.5 * hour + 1 * hour,
    matureSeconds: 3.5 * hour,
    collectWindowSeconds: defaultCollectWindowSeconds,
    baseYieldGold: 360,
    strategyNote: '高收益种，用来制造“等还是收”的核心博弈。',
    lore: '藤蔓天生细密纹路，如牵机阵法，常被低阶阵法师采作材料。',
  },
  {
    seedId: 'huichuncao',
    label: '回春草',
    rarity: 'rare',
    sortOrder: 110,
    growSeconds: 3 * hour + 1 * hour,
    matureSeconds: 4 * hour,
    collectWindowSeconds: defaultCollectWindowSeconds,
    baseYieldGold: 480,
    strategyNote: '回种保值种，服务上线不稳但不想亏的玩家。',
    lore: '草叶卷曲如初春嫩芽，折断后会迅速渗出淡绿汁液。',
  },
  {
    seedId: 'xueyuehua',
    label: '雪月花',
    rarity: 'rare',
    sortOrder: 120,
    growSeconds: 2.5 * hour + 1 * hour,
    matureSeconds: 3.5 * hour,
    collectWindowSeconds: defaultCollectWindowSeconds,
    baseYieldGold: 760,
    strategyNote: '高成熟收益种，适合高活跃和高风险偏好的玩家。',
    lore: '只在高寒雪山顶的月圆之夜盛开，花瓣冰白带银纹。',
  },
  {
    seedId: 'jingdaosong',
    label: '劲道松',
    rarity: 'rare',
    sortOrder: 130,
    growSeconds: 4 * hour + 1 * hour,
    matureSeconds: 5 * hour,
    collectWindowSeconds: defaultCollectWindowSeconds,
    baseYieldGold: 620,
    strategyNote: '长周期高保值种，适合赛季后段稳定囤种和慢收策略。',
    lore: '松针坚韧如弦，枝干久经风霜仍能蓄住灵气。',
  },
  {
    seedId: 'hundunguo',
    label: '混沌果',
    rarity: 'rare',
    sortOrder: 140,
    growSeconds: 4 * hour + 1.5 * hour,
    matureSeconds: 5.5 * hour,
    collectWindowSeconds: defaultCollectWindowSeconds,
    baseYieldGold: 880,
    strategyNote: '后期抽水种，适合作为强回收和高价值诱盗目标。',
    lore: '果壳灰黑，纹理难辨，成熟时会散出浑浊灵雾。',
  },
  {
    seedId: 'zhanqingsi',
    label: '斩情丝',
    rarity: 'legendary',
    sortOrder: 210,
    growSeconds: 3 * hour + 1 * hour,
    matureSeconds: 4 * hour,
    collectWindowSeconds: defaultCollectWindowSeconds,
    baseYieldGold: 1200,
    strategyNote: '高风险斩杀种，高收益与高失败代价都很极端。',
    lore: '细丝似藤非藤，传说能斩断心魔，也会牵出旧念。',
  },
  {
    seedId: 'wangchuanying',
    label: '忘川影',
    rarity: 'legendary',
    sortOrder: 220,
    growSeconds: 5 * hour + 1 * hour,
    matureSeconds: 6 * hour,
    collectWindowSeconds: defaultCollectWindowSeconds,
    baseYieldGold: 1200,
    strategyNote: '长周期隐性暴利种，适合赛季后段高投入慢兑现。',
    lore: '叶影如水面倒映，近看却空无一物。',
  },
  {
    seedId: 'zhaoyouming',
    label: '照幽冥',
    rarity: 'legendary',
    sortOrder: 230,
    growSeconds: 4 * hour + 1 * hour,
    matureSeconds: 5 * hour,
    collectWindowSeconds: defaultCollectWindowSeconds,
    baseYieldGold: 1600,
    strategyNote: '极限成熟回种种，负责把终局上线卡点收益推到天花板。',
    lore: '通体漆黑，夜里发出微弱青光，能照亮脚下三尺的地气。',
  },
];
