import type { SpiritRarity, SpiritRole } from '@prisma/client';

export interface SpiritDefinitionSeedData {
  spiritId: string;
  label: string;
  rarity: SpiritRarity;
  factionAffinity: 'human' | 'immortal' | 'demon';
  role: SpiritRole;
  shardName: string;
  shardUnlockRequired: number;
  baseAttack: number;
  baseDefense: number;
  baseHp: number;
  growthAttack: number;
  growthDefense: number;
  growthHp: number;
  sortOrder: number;
  lore: string;
}

export const STARTER_SPIRIT_IDS = ['canglang', 'linglu', 'qingyuan'] as const;
export const DEFAULT_STARTER_SPIRIT_ID = STARTER_SPIRIT_IDS[0];
export const SPIRIT_SLOT_COUNT = 5;
export const SPIRIT_SHARD_CAP = 100;

export const SPIRIT_DEFINITION_SEEDS: SpiritDefinitionSeedData[] = [
  {
    spiritId: 'canglang',
    label: 'Canglang',
    rarity: 'COMMON',
    factionAffinity: 'human',
    role: 'ATTACK',
    shardName: 'Canglang Shard',
    shardUnlockRequired: SPIRIT_SHARD_CAP,
    baseAttack: 18,
    baseDefense: 10,
    baseHp: 120,
    growthAttack: 6,
    growthDefense: 3,
    growthHp: 24,
    sortOrder: 10,
    lore: 'A fast starter spirit suited for early attacks.',
  },
  {
    spiritId: 'xuanhu',
    label: 'Xuanhu',
    rarity: 'COMMON',
    factionAffinity: 'demon',
    role: 'ATTACK',
    shardName: 'Xuanhu Shard',
    shardUnlockRequired: SPIRIT_SHARD_CAP,
    baseAttack: 20,
    baseDefense: 8,
    baseHp: 115,
    growthAttack: 7,
    growthDefense: 3,
    growthHp: 22,
    sortOrder: 20,
    lore: 'A pressure-focused tiger spirit with strong early burst.',
  },
  {
    spiritId: 'linglu',
    label: 'Linglu',
    rarity: 'COMMON',
    factionAffinity: 'immortal',
    role: 'DEFENSE',
    shardName: 'Linglu Shard',
    shardUnlockRequired: SPIRIT_SHARD_CAP,
    baseAttack: 12,
    baseDefense: 18,
    baseHp: 135,
    growthAttack: 4,
    growthDefense: 6,
    growthHp: 28,
    sortOrder: 30,
    lore: 'A steady defensive starter spirit.',
  },
  {
    spiritId: 'qingyuan',
    label: 'Qingyuan',
    rarity: 'COMMON',
    factionAffinity: 'human',
    role: 'BALANCED',
    shardName: 'Qingyuan Shard',
    shardUnlockRequired: SPIRIT_SHARD_CAP,
    baseAttack: 15,
    baseDefense: 15,
    baseHp: 128,
    growthAttack: 5,
    growthDefense: 5,
    growthHp: 25,
    sortOrder: 40,
    lore: 'A balanced spirit for long-term starter growth.',
  },
  {
    spiritId: 'hegui',
    label: 'Hegui',
    rarity: 'COMMON',
    factionAffinity: 'human',
    role: 'DEFENSE',
    shardName: 'Hegui Shard',
    shardUnlockRequired: SPIRIT_SHARD_CAP,
    baseAttack: 10,
    baseDefense: 20,
    baseHp: 150,
    growthAttack: 3,
    growthDefense: 6,
    growthHp: 30,
    sortOrder: 50,
    lore: 'A durable shell-backed spirit for stable defense.',
  },
  {
    spiritId: 'shuanghu',
    label: 'Shuanghu',
    rarity: 'COMMON',
    factionAffinity: 'immortal',
    role: 'BALANCED',
    shardName: 'Shuanghu Shard',
    shardUnlockRequired: SPIRIT_SHARD_CAP,
    baseAttack: 14,
    baseDefense: 14,
    baseHp: 122,
    growthAttack: 5,
    growthDefense: 5,
    growthHp: 24,
    sortOrder: 60,
    lore: 'A light spirit built around scouting and counterplay.',
  },
  {
    spiritId: 'yingbao',
    label: 'Yingbao',
    rarity: 'COMMON',
    factionAffinity: 'demon',
    role: 'ATTACK',
    shardName: 'Yingbao Shard',
    shardUnlockRequired: SPIRIT_SHARD_CAP,
    baseAttack: 19,
    baseDefense: 9,
    baseHp: 118,
    growthAttack: 7,
    growthDefense: 3,
    growthHp: 23,
    sortOrder: 70,
    lore: 'A fast assault spirit with high offensive pressure.',
  },
  {
    spiritId: 'yundiao',
    label: 'Yundiao',
    rarity: 'COMMON',
    factionAffinity: 'immortal',
    role: 'ATTACK',
    shardName: 'Yundiao Shard',
    shardUnlockRequired: SPIRIT_SHARD_CAP,
    baseAttack: 17,
    baseDefense: 11,
    baseHp: 116,
    growthAttack: 6,
    growthDefense: 4,
    growthHp: 23,
    sortOrder: 80,
    lore: 'An agile sky spirit with strong initiative.',
  },
  {
    spiritId: 'shanxiong',
    label: 'Shanxiong',
    rarity: 'COMMON',
    factionAffinity: 'demon',
    role: 'HEALTH',
    shardName: 'Shanxiong Shard',
    shardUnlockRequired: SPIRIT_SHARD_CAP,
    baseAttack: 13,
    baseDefense: 15,
    baseHp: 165,
    growthAttack: 4,
    growthDefense: 5,
    growthHp: 34,
    sortOrder: 90,
    lore: 'A high-health frontline spirit with forgiving combat flow.',
  },
  {
    spiritId: 'chenghuang',
    label: 'Chenghuang',
    rarity: 'RARE',
    factionAffinity: 'immortal',
    role: 'DEFENSE',
    shardName: 'Chenghuang Shard',
    shardUnlockRequired: SPIRIT_SHARD_CAP,
    baseAttack: 16,
    baseDefense: 24,
    baseHp: 180,
    growthAttack: 5,
    growthDefense: 8,
    growthHp: 36,
    sortOrder: 110,
    lore: 'A rare guardian spirit with notable defensive value.',
  },
  {
    spiritId: 'guishou',
    label: 'Guishou',
    rarity: 'RARE',
    factionAffinity: 'human',
    role: 'BALANCED',
    shardName: 'Guishou Shard',
    shardUnlockRequired: SPIRIT_SHARD_CAP,
    baseAttack: 20,
    baseDefense: 18,
    baseHp: 160,
    growthAttack: 7,
    growthDefense: 6,
    growthHp: 32,
    sortOrder: 120,
    lore: 'A tactical rare spirit that favors flexible combat plans.',
  },
  {
    spiritId: 'xuangui',
    label: 'Xuangui',
    rarity: 'RARE',
    factionAffinity: 'immortal',
    role: 'DEFENSE',
    shardName: 'Xuangui Shard',
    shardUnlockRequired: SPIRIT_SHARD_CAP,
    baseAttack: 14,
    baseDefense: 26,
    baseHp: 190,
    growthAttack: 5,
    growthDefense: 9,
    growthHp: 38,
    sortOrder: 130,
    lore: 'A patient defensive spirit with strong endurance.',
  },
  {
    spiritId: 'taowu',
    label: 'Taowu',
    rarity: 'RARE',
    factionAffinity: 'demon',
    role: 'ATTACK',
    shardName: 'Taowu Shard',
    shardUnlockRequired: SPIRIT_SHARD_CAP,
    baseAttack: 28,
    baseDefense: 12,
    baseHp: 150,
    growthAttack: 9,
    growthDefense: 4,
    growthHp: 30,
    sortOrder: 140,
    lore: 'A ferocious rare spirit built for burst damage.',
  },
  {
    spiritId: 'dangchang',
    label: 'Dangchang',
    rarity: 'RARE',
    factionAffinity: 'human',
    role: 'HEALTH',
    shardName: 'Dangchang Shard',
    shardUnlockRequired: SPIRIT_SHARD_CAP,
    baseAttack: 18,
    baseDefense: 18,
    baseHp: 210,
    growthAttack: 6,
    growthDefense: 6,
    growthHp: 42,
    sortOrder: 150,
    lore: 'A rare vitality spirit with a large health pool.',
  },
  {
    spiritId: 'zhuyan',
    label: 'Zhuyan',
    rarity: 'RARE',
    factionAffinity: 'demon',
    role: 'ATTACK',
    shardName: 'Zhuyan Shard',
    shardUnlockRequired: SPIRIT_SHARD_CAP,
    baseAttack: 27,
    baseDefense: 14,
    baseHp: 155,
    growthAttack: 9,
    growthDefense: 5,
    growthHp: 31,
    sortOrder: 160,
    lore: 'A battle-hardened rare spirit for high-intensity clashes.',
  },
  {
    spiritId: 'fenghuang',
    label: 'Fenghuang',
    rarity: 'LEGENDARY',
    factionAffinity: 'immortal',
    role: 'DEFENSE',
    shardName: 'Fenghuang Shard',
    shardUnlockRequired: SPIRIT_SHARD_CAP,
    baseAttack: 28,
    baseDefense: 38,
    baseHp: 260,
    growthAttack: 9,
    growthDefense: 13,
    growthHp: 52,
    sortOrder: 210,
    lore: 'A legendary immortal guardian spirit.',
  },
  {
    spiritId: 'xueyan',
    label: 'Xueyan',
    rarity: 'LEGENDARY',
    factionAffinity: 'demon',
    role: 'ATTACK',
    shardName: 'Xueyan Shard',
    shardUnlockRequired: SPIRIT_SHARD_CAP,
    baseAttack: 42,
    baseDefense: 22,
    baseHp: 235,
    growthAttack: 14,
    growthDefense: 8,
    growthHp: 47,
    sortOrder: 220,
    lore: 'A legendary demon spirit with extreme pressure.',
  },
  {
    spiritId: 'yinglong',
    label: 'Yinglong',
    rarity: 'LEGENDARY',
    factionAffinity: 'human',
    role: 'HEALTH',
    shardName: 'Yinglong Shard',
    shardUnlockRequired: SPIRIT_SHARD_CAP,
    baseAttack: 32,
    baseDefense: 30,
    baseHp: 300,
    growthAttack: 10,
    growthDefense: 10,
    growthHp: 60,
    sortOrder: 230,
    lore: 'A legendary human-realm protector with exceptional endurance.',
  },
];
