import type { SpiritRarity, SpiritRole } from '@prisma/client';

export interface SpiritDefinitionSeedData {
  spiritId: string;
  label: string;
  rarity: SpiritRarity;
  factionAffinity: 'human' | 'immortal' | 'demon';
  role: SpiritRole;
  shardName: string;
  shardUnlockRequired: number;
  baseAttack: number;
  baseHp: number;
  growthAttack: number;
  growthHp: number;
  sortOrder: number;
  lore: string;
}

export const STARTER_SPIRIT_IDS = ['canglang', 'linglu', 'qingyuan'] as const;
export const DEFAULT_STARTER_SPIRIT_ID = STARTER_SPIRIT_IDS[0];
export const SPIRIT_SLOT_COUNT = 5;
export const COMMON_SPIRIT_SHARD_REQUIREMENT = 20;
export const RARE_SPIRIT_SHARD_REQUIREMENT = 60;
export const LEGENDARY_SPIRIT_SHARD_REQUIREMENT = 100;

export const SPIRIT_DEFINITION_SEEDS: SpiritDefinitionSeedData[] = [
  {
    spiritId: 'canglang',
    label: '苍狼',
    rarity: 'COMMON',
    factionAffinity: 'human',
    role: 'ATTACK',
    shardName: '苍狼精魄',
    shardUnlockRequired: COMMON_SPIRIT_SHARD_REQUIREMENT,
    baseAttack: 18,
    baseHp: 120,
    growthAttack: 6,
    growthHp: 24,
    sortOrder: 10,
    lore: '山野游猎的铁爪狼，起手快，适合承担新手第一只输出宠定位。',
  },
  {
    spiritId: 'xuanhu',
    label: '玄虎',
    rarity: 'COMMON',
    factionAffinity: 'demon',
    role: 'ATTACK',
    shardName: '玄虎精魄',
    shardUnlockRequired: COMMON_SPIRIT_SHARD_REQUIREMENT,
    baseAttack: 20,
    baseHp: 115,
    growthAttack: 7,
    growthHp: 22,
    sortOrder: 20,
    lore: '黑纹煞虎，扑杀凶猛，强调前段爆发和压制感。',
  },
  {
    spiritId: 'linglu',
    label: '灵鹿',
    rarity: 'COMMON',
    factionAffinity: 'immortal',
    role: 'HEALTH',
    shardName: '灵鹿精魄',
    shardUnlockRequired: COMMON_SPIRIT_SHARD_REQUIREMENT,
    baseAttack: 12,
    baseHp: 135,
    growthAttack: 4,
    growthHp: 28,
    sortOrder: 30,
    lore: '饮露纳灵的山林灵兽，站场稳，适合防守向培养。',
  },
  {
    spiritId: 'qingyuan',
    label: '青猿',
    rarity: 'COMMON',
    factionAffinity: 'human',
    role: 'BALANCED',
    shardName: '青猿精魄',
    shardUnlockRequired: COMMON_SPIRIT_SHARD_REQUIREMENT,
    baseAttack: 15,
    baseHp: 128,
    growthAttack: 5,
    growthHp: 25,
    sortOrder: 40,
    lore: '善于周旋和持续缠斗，成长平滑，适合长期陪跑。',
  },
  {
    spiritId: 'hegui',
    label: '岩龟',
    rarity: 'COMMON',
    factionAffinity: 'human',
    role: 'HEALTH',
    shardName: '岩龟精魄',
    shardUnlockRequired: COMMON_SPIRIT_SHARD_REQUIREMENT,
    baseAttack: 10,
    baseHp: 150,
    growthAttack: 3,
    growthHp: 30,
    sortOrder: 50,
    lore: '岩甲厚重、正面抗压稳定，适合作为耐久型过渡宠。',
  },
  {
    spiritId: 'shuanghu',
    label: '霜狐',
    rarity: 'COMMON',
    factionAffinity: 'immortal',
    role: 'BALANCED',
    shardName: '霜狐精魄',
    shardUnlockRequired: COMMON_SPIRIT_SHARD_REQUIREMENT,
    baseAttack: 14,
    baseHp: 122,
    growthAttack: 5,
    growthHp: 24,
    sortOrder: 60,
    lore: '擅长拉扯与消耗，速度观感轻巧，适合侦查与反制氛围。',
  },
  {
    spiritId: 'yingbao',
    label: '影豹',
    rarity: 'COMMON',
    factionAffinity: 'demon',
    role: 'ATTACK',
    shardName: '影豹精魄',
    shardUnlockRequired: COMMON_SPIRIT_SHARD_REQUIREMENT,
    baseAttack: 19,
    baseHp: 118,
    growthAttack: 7,
    growthHp: 23,
    sortOrder: 70,
    lore: '突进迅猛、击杀欲强，是典型高压进攻型普通宠。',
  },
  {
    spiritId: 'yundiao',
    label: '云鹰',
    rarity: 'COMMON',
    factionAffinity: 'immortal',
    role: 'ATTACK',
    shardName: '云鹰精魄',
    shardUnlockRequired: COMMON_SPIRIT_SHARD_REQUIREMENT,
    baseAttack: 17,
    baseHp: 116,
    growthAttack: 6,
    growthHp: 23,
    sortOrder: 80,
    lore: '高空俯冲、先手感强，适合做高机动代表。',
  },
  {
    spiritId: 'shanxiong',
    label: '山熊',
    rarity: 'COMMON',
    factionAffinity: 'demon',
    role: 'HEALTH',
    shardName: '山熊精魄',
    shardUnlockRequired: COMMON_SPIRIT_SHARD_REQUIREMENT,
    baseAttack: 13,
    baseHp: 165,
    growthAttack: 4,
    growthHp: 34,
    sortOrder: 90,
    lore: '体魄沉重、正面硬撼能力强，容错高，适合站桩推进。',
  },
  {
    spiritId: 'chenghuang',
    label: '乘黄',
    rarity: 'RARE',
    factionAffinity: 'immortal',
    role: 'HEALTH',
    shardName: '乘黄精魄',
    shardUnlockRequired: RARE_SPIRIT_SHARD_REQUIREMENT,
    baseAttack: 16,
    baseHp: 180,
    growthAttack: 5,
    growthHp: 36,
    sortOrder: 110,
    lore: '瑞兽气质鲜明，防守反制能力突出，适合作为仙界高阶门面。',
  },
  {
    spiritId: 'guishou',
    label: '讹兽',
    rarity: 'RARE',
    factionAffinity: 'human',
    role: 'BALANCED',
    shardName: '讹兽精魄',
    shardUnlockRequired: RARE_SPIRIT_SHARD_REQUIREMENT,
    baseAttack: 20,
    baseHp: 160,
    growthAttack: 7,
    growthHp: 32,
    sortOrder: 120,
    lore: '擅长迷惑与牵制，战斗表现偏灵巧，适合做战术宠。',
  },
  {
    spiritId: 'xuangui',
    label: '玄蛇',
    rarity: 'RARE',
    factionAffinity: 'immortal',
    role: 'HEALTH',
    shardName: '玄蛇精魄',
    shardUnlockRequired: RARE_SPIRIT_SHARD_REQUIREMENT,
    baseAttack: 14,
    baseHp: 190,
    growthAttack: 5,
    growthHp: 38,
    sortOrder: 130,
    lore: '玄鳞绕雾、气息绵长，越到后程越能撑住燃血压力。',
  },
  {
    spiritId: 'taowu',
    label: '狡',
    rarity: 'RARE',
    factionAffinity: 'demon',
    role: 'ATTACK',
    shardName: '狡精魄',
    shardUnlockRequired: RARE_SPIRIT_SHARD_REQUIREMENT,
    baseAttack: 28,
    baseHp: 150,
    growthAttack: 9,
    growthHp: 30,
    sortOrder: 140,
    lore: '凶性明显、爆发极高，是魔界典型突击宠。',
  },
  {
    spiritId: 'dangchang',
    label: '当康',
    rarity: 'RARE',
    factionAffinity: 'human',
    role: 'HEALTH',
    shardName: '当康精魄',
    shardUnlockRequired: RARE_SPIRIT_SHARD_REQUIREMENT,
    baseAttack: 18,
    baseHp: 210,
    growthAttack: 6,
    growthHp: 42,
    sortOrder: 150,
    lore: '象征丰壤与生机，血量表现扎实，适合厚血路线。',
  },
  {
    spiritId: 'zhuyan',
    label: '朱厌',
    rarity: 'RARE',
    factionAffinity: 'demon',
    role: 'ATTACK',
    shardName: '朱厌精魄',
    shardUnlockRequired: RARE_SPIRIT_SHARD_REQUIREMENT,
    baseAttack: 27,
    baseHp: 155,
    growthAttack: 9,
    growthHp: 31,
    sortOrder: 160,
    lore: '战意浓烈、擅长硬碰硬，对高强度对撞场景有很强辨识度。',
  },
  {
    spiritId: 'fenghuang',
    label: '凤皇',
    rarity: 'LEGENDARY',
    factionAffinity: 'immortal',
    role: 'HEALTH',
    shardName: '凤皇精魄',
    shardUnlockRequired: LEGENDARY_SPIRIT_SHARD_REQUIREMENT,
    baseAttack: 28,
    baseHp: 260,
    growthAttack: 9,
    growthHp: 52,
    sortOrder: 210,
    lore: '仙界至尊灵禽，兼具威仪与护佑感，适合作为顶级防守反制型传说宠。',
  },
  {
    spiritId: 'xueyan',
    label: '血魇',
    rarity: 'LEGENDARY',
    factionAffinity: 'demon',
    role: 'ATTACK',
    shardName: '血魇精魄',
    shardUnlockRequired: LEGENDARY_SPIRIT_SHARD_REQUIREMENT,
    baseAttack: 42,
    baseHp: 235,
    growthAttack: 14,
    growthHp: 47,
    sortOrder: 220,
    lore: '魔界至凶邪兽，气质更黑暗、更凶煞，主打极强压制与终局斩杀感。',
  },
  {
    spiritId: 'yinglong',
    label: '应龙',
    rarity: 'LEGENDARY',
    factionAffinity: 'human',
    role: 'HEALTH',
    shardName: '应龙精魄',
    shardUnlockRequired: LEGENDARY_SPIRIT_SHARD_REQUIREMENT,
    baseAttack: 32,
    baseHp: 300,
    growthAttack: 10,
    growthHp: 60,
    sortOrder: 230,
    lore: '人界护世神龙，血量与持续作战表现突出，适合作为长期主养核心。',
  },
];

export const COMMON_NON_STARTER_SPIRIT_IDS = SPIRIT_DEFINITION_SEEDS
  .filter((spirit) => spirit.rarity === 'COMMON' && !STARTER_SPIRIT_IDS.includes(spirit.spiritId as typeof STARTER_SPIRIT_IDS[number]))
  .map((spirit) => spirit.spiritId);
