INSERT INTO "seed_definition" (
  "id",
  "seed_id",
  "label",
  "rarity",
  "sort_order",
  "seed_seconds",
  "grow_seconds",
  "mature_seconds",
  "ripe_window_seconds",
  "base_yield_gold",
  "harvest_seed_return",
  "strategy_note",
  "lore",
  "created_at",
  "updated_at"
) VALUES (
  'seeddef_xunyamai',
  'xunyamai',
  '风云稻',
  'common',
  20,
  900,
  900,
  1800,
  1800,
  200,
  2,
  '半小时快收种，适合碎片时间上线后迅速完成一轮收益。',
  '稻芒起势极快，晨起沾露便能成势，半个时辰内就能完成一轮收益。',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT ("seed_id") DO UPDATE SET
  "label" = EXCLUDED."label",
  "rarity" = EXCLUDED."rarity",
  "sort_order" = EXCLUDED."sort_order",
  "seed_seconds" = EXCLUDED."seed_seconds",
  "grow_seconds" = EXCLUDED."grow_seconds",
  "mature_seconds" = EXCLUDED."mature_seconds",
  "ripe_window_seconds" = EXCLUDED."ripe_window_seconds",
  "base_yield_gold" = EXCLUDED."base_yield_gold",
  "harvest_seed_return" = EXCLUDED."harvest_seed_return",
  "strategy_note" = EXCLUDED."strategy_note",
  "lore" = EXCLUDED."lore",
  "updated_at" = CURRENT_TIMESTAMP;
