export enum ErrorCode {
  BadRequest = 'BAD_REQUEST',
  Unauthorized = 'UNAUTHORIZED',
  Forbidden = 'FORBIDDEN',
  NotFound = 'NOT_FOUND',
  Conflict = 'CONFLICT',
  NoPendingClaim = 'NO_PENDING_CLAIM',
  TaskNotFound = 'TASK_NOT_FOUND',
  TaskNotCompleted = 'TASK_NOT_COMPLETED',
  TaskAlreadyClaimed = 'TASK_ALREADY_CLAIMED',
  ArmyCapacityExceeded = 'ARMY_CAPACITY_EXCEEDED',
  TrainingQueueExists = 'TRAINING_QUEUE_EXISTS',
  ArmyStateChanged = 'ARMY_STATE_CHANGED',
  FieldLocked = 'FIELD_LOCKED',
  FieldNotCollectable = 'FIELD_NOT_COLLECTABLE',
  FieldStatusChanged = 'FIELD_STATUS_CHANGED',
  InsufficientVaultGold = 'INSUFFICIENT_VAULT_GOLD',
  InsufficientArmy = 'INSUFFICIENT_ARMY',
  RaidTargetNotFound = 'RAID_TARGET_NOT_FOUND',
  RaidTargetExpired = 'RAID_TARGET_EXPIRED',
  ProtectionActive = 'PROTECTION_ACTIVE',
  RaidNotAllowed = 'RAID_NOT_ALLOWED',
  SeasonRolledOver = 'SEASON_ROLLED_OVER',
  StateVersionConflict = 'STATE_VERSION_CONFLICT',
  ConfigurationError = 'CONFIGURATION_ERROR',
  PrismaClientUnavailable = 'PRISMA_CLIENT_UNAVAILABLE',
  InternalServerError = 'INTERNAL_SERVER_ERROR',
}
