ALTER TYPE "SocialFeedType" ADD VALUE IF NOT EXISTS 'FRIEND_REQUESTED';
ALTER TYPE "SocialFeedType" ADD VALUE IF NOT EXISTS 'FRIEND_ACCEPTED';
ALTER TYPE "SocialFeedType" ADD VALUE IF NOT EXISTS 'FRIEND_REJECTED';
