import { APP_NAME, type ClientBootstrapResponse, type ClientDailyTaskSummary, type ClientFarmField, type ClientRaidMessageTemplate, type ClientRaidTargetDetailResponse, type ClientSceneContentResponse, type HomeSummaryResponse } from '@trinitywar/shared';

import type { ClientRaidSpiritPreview } from '@trinitywar/shared';

const raidFieldCompatMarker = null as ClientFarmField | null;
void raidFieldCompatMarker;

const mockDailyTasks: ClientDailyTaskSummary[] = [
  {
    id: 'daily-harvest-once',
    title: '收取 1 次成熟田地',
    description: '经营任务，完成后可领取 18 金币。',
    progressCurrent: 0,
    progressTarget: 1,
    progressText: '0/1',
    rewardGold: 18,
    status: 'in-progress',
    actionScene: 'farm',
  },
  {
    id: 'daily-start-cultivation',
    title: '完成 1 次播种',
    description: '经营任务，完成后可领取 16 金币。',
    progressCurrent: 0,
    progressTarget: 1,
    progressText: '0/1',
    rewardGold: 16,
    status: 'in-progress',
    actionScene: 'farm',
  },
  {
    id: 'daily-recruit-army',
    title: '征召 1 次士兵',
    description: '经营任务，完成后可领取 18 金币。',
    progressCurrent: 0,
    progressTarget: 1,
    progressText: '0/1',
    rewardGold: 18,
    status: 'in-progress',
    actionScene: 'raid',
  },
];

export const mockRaidMessageTemplates: ClientRaidMessageTemplate[] = [
  { templateId: 'steady-harvest', text: '今日借一程，来日还一礼。' },
  { templateId: 'field-well-kept', text: '田照顾得不错，我记下了。' },
  { templateId: 'next-time-guard', text: '下次记得把成熟田守紧。' },
  { templateId: 'fair-raid', text: '各凭本事，不伤和气。' },
  { templateId: 'come-again', text: '这次收下了，改日再会。' },
];

const mockRaidSpiritPreviews: Record<string, ClientRaidSpiritPreview> = {
  'target-1': { spiritId: 'yingbao', sceneVisibility: 'named', displayName: '影豹', label: '影豹', level: 9, rarity: 'common', avatarGlyph: '影' },
  'target-2': { spiritId: 'linglu', sceneVisibility: 'named', displayName: '灵鹿', label: '灵鹿', level: 8, rarity: 'common', avatarGlyph: '鹿' },
  'target-3': { spiritId: 'qingyuan', sceneVisibility: 'named', displayName: '青猿', label: '青猿', level: 6, rarity: 'common', avatarGlyph: '猿' },
  'target-4': { spiritId: 'xuanhu', sceneVisibility: 'named', displayName: '玄虎', label: '玄虎', level: 11, rarity: 'common', avatarGlyph: '虎' },
  'target-5': { spiritId: 'shuanghu', sceneVisibility: 'named', displayName: '霜狐', label: '霜狐', level: 5, rarity: 'common', avatarGlyph: '狐' },
};

export const mockBootstrap: ClientBootstrapResponse = {
  app: APP_NAME,
  env: 'local',
  version: '0.1.0',
  serverTime: new Date('2026-05-09T10:00:00+08:00').toISOString(),
  season: {
    seasonNumber: 3,
    currentWeek: 1,
    totalWeeks: 4,
  },
  backpack: {
    seedInventory: {
      qilingya: 1,
      qinglingmai: 0,
      xunyamai: 0,
      ninglucao: 0,
      suixinhua: 0,
      baiyulian: 0,
      yingyuezhu: 0,
      qianjiteng: 0,
      huichuncao: 0,
      xueyuehua: 0,
      jingdaosong: 0,
      hundunguo: 0,
      zhanqingsi: 0,
      wangchuanying: 0,
      zhaoyouming: 0,
    },
    essenceInventory: {
      qilingya: 1,
      qinglingmai: 0,
      xunyamai: 0,
      ninglucao: 0,
      suixinhua: 0,
      baiyulian: 0,
      yingyuezhu: 0,
      qianjiteng: 0,
      huichuncao: 0,
      xueyuehua: 0,
      jingdaosong: 0,
      hundunguo: 0,
      zhanqingsi: 0,
      wangchuanying: 0,
      zhaoyouming: 0,
    },
    globalItemInventory: {
      spiritSoul: 0,
      tianjiTalisman: 0,
    },
    unlockedSeedIds: ['qilingya'],
    unlockedPlantIds: ['qilingya'],
    starterSeedClaimed: false,
    tianjiTalismanClaimed: false,
    spiritSoulClaimed: false,
    dailySpiritSoulAmount: 4,
  },
};

export const mockHomeSummary: HomeSummaryResponse = {
  app: APP_NAME,
  playerName: '人界领主·临川',
  factionName: '人界',
  castleLevel: 4,
  stateVersions: {
    buildingVersion: 1,
    walletVersion: 1,
    armyVersion: 1,
  },
  staminaStatus: '免费战斗 2/3',
  fieldStatus: '成熟田地 1 块，成熟中 1 块',
  reportStatus: '探索动态 2，免费复仇 1',
  protectedUntil: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
  resources: [
    { label: '金币', value: '4,990', tone: 'vault' },
    { label: '灵宠', value: '40 / 100', tone: 'army' },
  ],
  pendingClaims: [],
  temporaryClaim: null,
  dailyTasks: mockDailyTasks,
  factionTasks: [],
  todayContribution: 0,
  primaryActions: [
    { key: 'building', title: '法术阁', description: '修习法术强化经营' },
    { key: 'farm', title: '农场', description: '收成熟田地' },
    { key: 'raid', title: '灵宠', description: '培育灵宠并查看当前守备' },
    { key: 'report', title: '探索', description: '查看目标与战报' },
    { key: 'faction', title: '阵营', description: '查看贡献并领取俸禄' },
  ],
};

export const mockSceneContent: ClientSceneContentResponse = {
  app: APP_NAME,
  building: {
    upgrades: [],
    extensions: [
      {
        id: 'protectionTech',
        title: '护灵阵',
        levelText: 'Lv.0 -> Lv.1',
        description: '结阵护住灵田与本命灵宠，延长被挑战成功后的保护时间。',
        effectText: '当前 0 分钟，修习后 10 分钟。',
        costText: '消耗 320 金币',
        action: { label: '修习法术', target: 'building', tone: 'secondary' },
      },
      {
        id: 'farmYieldTech',
        title: '祈雨术',
        levelText: 'Lv.0 -> Lv.1',
        description: '引灵雨滋养田垄，提升作物培育与成熟阶段的金币收益。',
        effectText: '当前 0%，修习后 2%。',
        costText: '消耗 400 金币',
        action: { label: '修习法术', target: 'building', tone: 'secondary' },
      },
      {
        id: 'collectWindowTech',
        title: '观星术',
        levelText: 'Lv.0 -> Lv.1',
        description: '观天象定农时，延长作物成熟后的可收窗口。',
        effectText: '当前 0 分钟，修习后 5 分钟。',
        costText: '消耗 360 金币',
        action: { label: '修习法术', target: 'building', tone: 'secondary' },
      },
    ],
  },
  army: {
    unitCostGold: 100,
    unitTrainingSeconds: 60,
    queue: null,
  },
  farm: {
    hero: {
      eyebrow: '田地经营',
      title: '成熟 1 块 · 成熟中 2 块',
      description: '农场以田地为主，点击空地即可继续播种，成熟后直接收取。',
      action: { label: '开始培育', target: 'farm', tone: 'primary' },
    },
    fields: [
      {
        id: 'field-1',
        code: '田地 01',
        title: '成熟期',
        badge: '成熟',
        cropName: '青灵麦',
        tone: 'mature',
        progressRemainingSeconds: 0,
        progressTotalSeconds: 1,
        yieldGold: 1260,
        description: '点击收取，触发爆金币并结算本轮成熟收益。',
        actions: [
          { label: '收取', target: 'farm', tone: 'primary' },
        ],
      },
      {
        id: 'field-2',
        code: '田地 02',
        title: '培育中',
        badge: '培育',
        cropName: '青灵麦',
        tone: 'growing',
        progressRemainingSeconds: 2535,
        progressTotalSeconds: 3600,
        yieldGold: 420,
        description: '作物培育中，成熟后即可收取。',
        actions: [],
      },
      {
        id: 'field-3',
        code: '田地 03',
        title: '成熟期',
        badge: '成熟',
        cropName: '青灵麦',
        tone: 'growing',
        progressRemainingSeconds: 4690,
        progressTotalSeconds: 7200,
        yieldGold: 660,
        description: '可抢收，点击后直接结算一轮收取结果。',
        actions: [
          { label: '收取', target: 'farm', tone: 'secondary' },
        ],
      },
      {
        id: 'field-4',
        code: '田地 04',
        title: '未解锁',
        badge: '待解锁',
        cropName: undefined,
        tone: 'locked',
        progressRemainingSeconds: 0,
        progressTotalSeconds: 1,
        yieldGold: 0,
        description: '初始开放，可直接播种。',
        actions: [],
      },
    ],
    landDeeds: [],
    guide: {
      title: '农场线引导',
      description: '以后如果农场增加培育品类、天气、地块事件和成熟策略，都可以继续在这个页面扩展。',
      actions: [
        { label: '打开主城页', target: 'building', tone: 'secondary' },
        { label: '返回首页', target: 'home', tone: 'ghost' },
      ],
    },
  },
  raid: {
    hero: {
      eyebrow: '可探索目标',
      title: '剩余免费战斗 2 / 3',
      description: '进入页面后先看目标列表，重点判断等级、阵营和当前值不值得出手。',
      action: { label: '刷新目标', target: 'raid', tone: 'secondary' },
    },
    targets: [
      {
        id: 'target-1',
        targetPlayerId: 'mock-player-target-1',
        name: '烬牙',
        faction: '魔界',
        level: 5,
        mainPetPreview: mockRaidSpiritPreviews['target-1'],
        combatPower: '1,320',
        summary: '魔界 · 资源高 · 防守偏弱',
        loot: '420~560 金币',
        risk: '高风险',
        detail: '成熟田 2 块 · 可争夺 520 · 今日被挑战 1 次',
        action: { label: '发起战斗', target: 'raid', tone: 'primary' },
      },
      {
        id: 'target-2',
        targetPlayerId: 'mock-player-target-2',
        name: '云栖',
        faction: '仙界',
        level: 4,
        mainPetPreview: mockRaidSpiritPreviews['target-2'],
        combatPower: '1,080',
        summary: '仙界 · 资源中 · 减损明显',
        loot: '260~340 金币',
        risk: '中风险',
        detail: '成熟田 1 块 · 可争夺 260 · 防守偏稳',
        action: { label: '发起战斗', target: 'raid', tone: 'secondary' },
      },
      {
        id: 'target-3',
        targetPlayerId: 'mock-player-target-3',
        name: '临风',
        faction: '人界',
        level: 4,
        mainPetPreview: mockRaidSpiritPreviews['target-3'],
        combatPower: '920',
        summary: '人界 · 资源低 · 风险较稳',
        loot: '180~260 金币',
        risk: '低风险',
        detail: '成长期 1 块 · 可争夺 180 · 适合保守出手',
        action: { label: '发起战斗', target: 'raid', tone: 'secondary' },
      },
      {
        id: 'target-4',
        targetPlayerId: 'mock-player-target-4',
        name: '玄潮',
        faction: '魔界',
        level: 5,
        mainPetPreview: mockRaidSpiritPreviews['target-4'],
        combatPower: '1,240',
        summary: '魔界 · 主宠等级高 · 默认仅见品种',
        loot: '360~480 金币',
        risk: '中高风险',
        detail: '成熟田 1 块 · 可争夺 460 · 守田灵宠分散',
        action: { label: '发起战斗', target: 'raid', tone: 'secondary' },
      },
      {
        id: 'target-5',
        targetPlayerId: 'mock-player-target-5',
        name: '青槐',
        faction: '仙界',
        level: 3,
        mainPetPreview: mockRaidSpiritPreviews['target-5'],
        combatPower: '760',
        summary: '仙界 · 主宠等级低 · 适合试探',
        loot: '150~220 金币',
        risk: '低风险',
        detail: '成熟田 1 块 · 可争夺 140 · 防守偏弱',
        action: { label: '发起战斗', target: 'raid', tone: 'secondary' },
      },
    ],
    detail: {
      advice: '默认先看等级和品种，若要决定是否越级，建议先做深度窥视。',
      actions: [
        { label: '调整灵宠', target: 'raid', tone: 'ghost' },
        { label: '确认派遣', target: 'raid', tone: 'primary' },
      ],
    },
    messageTemplates: mockRaidMessageTemplates,
  },
  report: {
    defense: [
      {
        title: '魔界 · 烬牙',
        tag: '小败 · 惜败而退',
        tone: 'danger',
        createdAt: new Date(Date.now() - 37 * 60 * 1000).toISOString(),
        unread: true,
        revengeable: true,
        summary: '37 分钟前对手以小胜拿走你 240 金币，并让你的主战灵宠进入明显损血状态。',
        actions: [
          { label: '查看详情', target: 'report', tone: 'ghost' },
          { label: '复仇', target: 'raid', tone: 'primary' },
        ],
      },
    ],
    attack: [
      {
        title: '匿名目标 · 赤砂营地',
        tag: '小胜 · 险取一筹',
        tone: 'success',
        createdAt: new Date(Date.now() - 58 * 60 * 1000).toISOString(),
        summary: '08:40 你以小胜拿到 436 金币和 6 颗兽魂，主战灵宠扣血 18%。',
        actions: [{ label: '查看详情', target: 'report', tone: 'ghost' }],
      },
      {
        title: '匿名目标 · 玄潮',
        tag: '大胜 · 势如破竹',
        tone: 'success',
        createdAt: new Date(Date.now() - 132 * 60 * 1000).toISOString(),
        summary: '07:06 你以大胜拿到 512 金币和 8 颗兽魂，主战灵宠仅扣血 11%。',
        actions: [{ label: '查看详情', target: 'report', tone: 'ghost' }],
      },
      {
        title: '匿名目标 · 云栖',
        tag: '相持 · 平分秋色',
        tone: 'neutral',
        createdAt: new Date(Date.now() - 205 * 60 * 1000).toISOString(),
        summary: '05:53 双方灵宠势均力敌，你只拿到少量金币与 3 颗兽魂，主战灵宠扣血 23%。',
        actions: [{ label: '查看详情', target: 'report', tone: 'ghost' }],
      },
    ],
    actions: [],
  },
  faction: {
    hero: {
      eyebrow: '阵营面板',
      title: '人界阵营',
      description: '完成日常行为积累个人贡献，每日按贡献档位领取材料俸禄。',
      advantage: '今日俸禄档位：入门俸禄',
      breakdown: '预计每日俸禄：金币 x20、灵根 x20、普通兽魂 x5',
      action: { label: '领取俸禄', target: 'faction', tone: 'primary' },
    },
    contribution: {
      title: '当前贡献值',
      value: '40',
      description: '贡献用于提升每日俸禄档位，俸禄以金币、随机灵宠碎片和分档兽魂为主。',
    },
    comparison: [
      { faction: '人界', advantage: '总贡献 1,260', totalContribution: '1,260', power: '1,260', isCurrent: true },
      { faction: '仙界', advantage: '总贡献 1,180', totalContribution: '1,180', power: '1,180' },
      { faction: '魔界', advantage: '总贡献 1,340', totalContribution: '1,340', power: '1,340' },
    ],
    donate: {
      title: '阵营贡献',
      description: '贡献主要来自种田、灵宠、互助和对战行为。',
      goldStep: 100,
      contributionRule: '当前没有资源兑换入口，贡献由日常行为积累。',
    },
    tasks: [],
    contributionLogs: [],
    stipend: {
      title: '每日阵营俸禄',
      description: '每日可按当前贡献档位领取一次，材料为主、少量金币为辅。',
      status: 'available',
      dateKey: new Date().toISOString().slice(0, 10),
      contribution: 40,
      tierKey: 'contribution-0',
      tierLabel: '入门俸禄',
      rewards: [
        { kind: 'gold', label: '金币', quantity: 20 },
        { kind: 'spirit-root', label: '灵根', quantity: 20 },
        { kind: 'ordinary-soul', label: '普通兽魂', quantity: 5 },
      ],
      claimedAt: null,
      action: { label: '领取俸禄', target: 'faction', tone: 'primary' },
    },
    rankings: [
      { playerId: 'mock-faction-player-1', rank: 1, label: '1. 临风', value: '86 贡献', note: 'Lv.5', factionName: '人界', contributionScore: 86, castleLevel: 5 },
      { playerId: 'mock-faction-player-2', rank: 2, label: '2. 青槐', value: '72 贡献', note: 'Lv.4', factionName: '人界', contributionScore: 72, castleLevel: 4 },
      { playerId: 'mock-current-player', rank: 3, label: '3. 你', value: '40 贡献', note: 'Lv.4', factionName: '人界', contributionScore: 40, castleLevel: 4, isCurrentPlayer: true },
    ],
  },
};

export const mockRaidTargetDetails: Record<string, ClientRaidTargetDetailResponse> = {
  'target-1': {
    app: APP_NAME,
    targetId: 'target-1',
    name: '烬牙',
    faction: '魔界',
    level: 5,
    combatPower: '1,320',
    raidRule: '探索与战斗只针对对手灵宠，奖励由系统按战果发放。',
    defenseStatus: '防守偏弱，守田灵宠少于常见同级目标',
    protectionStatus: '当前可挑战，是否结算成功以次数限制和最终原子校验为准',
    mainPetPreview: mockRaidSpiritPreviews['target-1'],
    remainingFreeIntel: 3,
    remainingTalismanIntel: 3,
    detail: '对手昵称烬牙，刚结束一轮农场收取，外露收益仍然较高。魔界加成偏向进攻，适合快速出手。',
    actions: [
      { label: '发起战斗', target: 'raid', tone: 'primary' },
    ],
  },
  'target-2': {
    app: APP_NAME,
    targetId: 'target-2',
    name: '云栖',
    faction: '仙界',
    level: 4,
    combatPower: '1,080',
    raidRule: '探索与战斗只针对对手灵宠，奖励由系统按战果发放。',
    defenseStatus: '防守偏稳，仙界被挑战损失减免明显',
    protectionStatus: '当前可挑战，普通目标不再使用时间保护期',
    mainPetPreview: mockRaidSpiritPreviews['target-2'],
    remainingFreeIntel: 3,
    remainingTalismanIntel: 3,
    detail: '对手昵称云栖，收益中等但仙界自带减损，适合先做一轮稳妥试探。',
    actions: [
      { label: '发起战斗', target: 'raid', tone: 'primary' },
    ],
  },
  'target-3': {
    app: APP_NAME,
    targetId: 'target-3',
    name: '临风',
    faction: '人界',
    level: 4,
    combatPower: '920',
    raidRule: '探索与战斗只针对对手灵宠，奖励由系统按战果发放。',
    defenseStatus: '人界经营向，防守一般，但暴露收益偏低',
    protectionStatus: '当前可挑战，胜负奖励取决于结果档位',
    mainPetPreview: mockRaidSpiritPreviews['target-3'],
    remainingFreeIntel: 3,
    remainingTalismanIntel: 3,
    detail: '对手昵称临风，收益较低，更适合作为保守出手对象。',
    actions: [
      { label: '发起战斗', target: 'raid', tone: 'primary' },
    ],
  },
  'target-4': {
    app: APP_NAME,
    targetId: 'target-4',
    name: '玄潮',
    faction: '魔界',
    level: 5,
    combatPower: '1,240',
    raidRule: '探索与战斗只针对对手灵宠，奖励由系统按战果发放。',
    defenseStatus: '中等防守，守备偏强但守田灵宠分散',
    protectionStatus: '挑战型目标，适合利用五行克制搏高收益',
    mainPetPreview: mockRaidSpiritPreviews['target-4'],
    remainingFreeIntel: 3,
    remainingTalismanIntel: 3,
    detail: '对手昵称玄潮，领地阶段高一档，收益不错，但正面强碰战损会更高。',
    actions: [
      { label: '发起战斗', target: 'raid', tone: 'primary' },
    ],
  },
  'target-5': {
    app: APP_NAME,
    targetId: 'target-5',
    name: '青槐',
    faction: '仙界',
    level: 3,
    combatPower: '760',
    raidRule: '探索与战斗只针对对手灵宠，奖励由系统按战果发放。',
    defenseStatus: '防守偏弱，适合低损验证',
    protectionStatus: '稳妥目标，适合低风险消耗免费次数',
    mainPetPreview: mockRaidSpiritPreviews['target-5'],
    remainingFreeIntel: 3,
    remainingTalismanIntel: 3,
    detail: '对手昵称青槐，适合低风险起手，重点看田地收益是否值得你消耗免费次数。',
    actions: [
      { label: '发起战斗', target: 'raid', tone: 'primary' },
    ],
  },
};
