import { APP_NAME, type ClientBootstrapResponse, type ClientDailyTaskSummary, type ClientFarmField, type ClientRaidMessageTemplate, type ClientRaidTargetDetailResponse, type ClientSceneContentResponse, type HomeSummaryResponse } from '@trinitywar/shared';

const mockDailyTasks: ClientDailyTaskSummary[] = [
  {
    id: 'daily-harvest-once',
    title: '收取 1 次成熟田地',
    description: '经营任务，完成后可领取 18 金币。',
    progressCurrent: 0,
    progressTarget: 1,
    progressText: '0/1',
    rewardGold: 18,
    status: 'in-progress',
    actionScene: 'farm',
  },
  {
    id: 'daily-start-cultivation',
    title: '完成 1 次播种',
    description: '经营任务，完成后可领取 16 金币。',
    progressCurrent: 0,
    progressTarget: 1,
    progressText: '0/1',
    rewardGold: 16,
    status: 'in-progress',
    actionScene: 'farm',
  },
  {
    id: 'daily-recruit-army',
    title: '培育 10 只灵宠',
    description: '经营任务，完成后可领取 20 金币。',
    progressCurrent: 0,
    progressTarget: 10,
    progressText: '0/10',
    rewardGold: 20,
    status: 'in-progress',
    actionScene: 'raid',
  },
];

function createRaidDetailField(field: Partial<ClientFarmField> & Pick<ClientFarmField, 'id' | 'code' | 'title' | 'badge' | 'tone' | 'description'>): ClientFarmField {
  return {
    progressRemainingSeconds: 0,
    progressTotalSeconds: 1,
    ...field,
    yieldGold: field.yieldGold ?? 0,
    actions: field.actions ?? [],
  };
}

export const mockRaidMessageTemplates: ClientRaidMessageTemplate[] = [
  { templateId: 'steady-harvest', text: '今日借一程，来日还一礼。' },
  { templateId: 'field-well-kept', text: '田照顾得不错，我记下了。' },
  { templateId: 'next-time-guard', text: '下次记得把成熟田守紧。' },
  { templateId: 'fair-raid', text: '各凭本事，不伤和气。' },
  { templateId: 'come-again', text: '这次收下了，改日再会。' },
];

export const mockBootstrap: ClientBootstrapResponse = {
  app: APP_NAME,
  env: 'local',
  version: '0.1.0',
  serverTime: new Date('2026-05-09T10:00:00+08:00').toISOString(),
  season: {
    seasonNumber: 3,
    currentWeek: 1,
    totalWeeks: 4,
  },
  backpack: {
    seedInventory: {
      qinglingmai: 0,
      ninglucao: 0,
      suixinhua: 0,
      baiyulian: 0,
      yingyuezhu: 0,
      qianjiteng: 0,
      huichuncao: 0,
      xueyuehua: 0,
      jingdaosong: 0,
      hundunguo: 0,
      zhanqingsi: 0,
      wangchuanying: 0,
      zhaoyouming: 0,
    },
    globalItemInventory: {
      tianjiTalisman: 0,
    },
    unlockedSeedIds: ['qinglingmai'],
    starterSeedClaimed: false,
    tianjiTalismanClaimed: false,
  },
};

export const mockHomeSummary: HomeSummaryResponse = {
  app: APP_NAME,
  playerName: '人界领主·临川',
  factionName: '人界',
  castleLevel: 4,
  stateVersions: {
    buildingVersion: 1,
    walletVersion: 1,
    armyVersion: 1,
  },
  staminaStatus: '免费掠夺 2/3',
  fieldStatus: '丰熟田地 1 块，成熟中 1 块',
  reportStatus: '掠夺动态 2，免费复仇 1',
  protectedUntil: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
  resources: [
    { label: '金币', value: '4,990 / 5,000', tone: 'vault' },
    { label: '灵宠', value: '40 / 100', tone: 'army' },
  ],
  pendingClaims: [
    { source: 'tax', label: '主城税收', value: '72', description: '当前每小时产出 18 金币，领取后直接入库。' },
    { source: 'faction', label: '阵营分红', value: '80', description: '当前每小时可分到 20 金币，来自阵营结算与贡献分档加成。' },
  ],
  temporaryClaim: null,
  dailyTasks: mockDailyTasks,
  primaryActions: [
    { key: 'building', title: '主城', description: '升级主城与金币容量' },
    { key: 'farm', title: '农场', description: '收丰熟田地' },
    { key: 'raid', title: '灵宠', description: '培育灵宠并查看当前守备' },
    { key: 'report', title: '掠夺', description: '查看目标、战报与通缉令' },
    { key: 'faction', title: '阵营', description: '上缴并查看分红' },
  ],
};

export const mockSceneContent: ClientSceneContentResponse = {
  app: APP_NAME,
  building: {
    upgrades: [
      {
        id: 'castle',
        title: '主城',
        description: 'Lv.4 -> Lv.5，主城税收由每小时 18 提升到 24。',
        costText: '消耗 1,800 金币',
        action: { label: '升级主城', target: 'building', tone: 'primary' },
      },
      {
        id: 'vault',
        title: '金币',
        description: 'Lv.3 -> Lv.4，容量由 5,000 提升到 6,600。',
        costText: '消耗 1,150 金币',
        action: { label: '升级金币上限', target: 'building', tone: 'secondary' },
      },
      {
        id: 'field-slot',
        title: '田地',
        description: '田地位不单独收费，会在主城达到对应等级时自动赠送开启。',
        costText: '需要主城 Lv.5',
        action: { label: '查看条件', target: 'building', tone: 'ghost' },
        locked: true,
      },
      {
        id: 'population',
        title: '灵宠上限',
        description: 'Lv.1 -> Lv.2，灵宠上限由 100 提升到 200。',
        costText: '消耗 180 金币',
        action: { label: '升级灵宠上限', target: 'building', tone: 'secondary' },
      },
      {
        id: 'watchtower',
        title: '防守',
        description: 'Lv.1 -> Lv.2，降低单次被掠比例并强化田地防守。',
        costText: '需要主城 Lv.5',
        locked: true,
        action: { label: '查看条件', target: 'building', tone: 'ghost' },
      },
    ],
    extensions: [
      {
        id: 'protectionTech',
        title: '护山结界',
        levelText: 'Lv.0 -> Lv.1',
        description: '延长被掠后的保护期，降低连续受击疲劳。',
        effectText: '当前 被掠保护期 +0 分钟，升级后 被掠保护期 +10 分钟。',
        costText: '需要主城 Lv.5',
        action: { label: '查看条件', target: 'building', tone: 'ghost' },
        locked: true,
      },
      {
        id: 'farmYieldTech',
        title: '灵脉灌溉',
        levelText: 'Lv.0 -> Lv.1',
        description: '提升田地成熟与丰熟收益，但不抬税收和分红。',
        effectText: '当前 田地收益 +0%，升级后 田地收益 +2%。',
        costText: '需要主城 Lv.5',
        action: { label: '查看条件', target: 'building', tone: 'ghost' },
        locked: true,
      },
      {
        id: 'ripeWindowTech',
        title: '时序观象台',
        levelText: 'Lv.0 -> Lv.1',
        description: '延长成熟窗口，降低错过高价值收取的挫败感。',
        effectText: '当前 成熟操作窗口 +0 分钟，升级后 成熟操作窗口 +5 分钟。',
        costText: '需要主城 Lv.8',
        action: { label: '查看条件', target: 'building', tone: 'ghost' },
        locked: true,
      },
      {
        id: 'pendingClaimTech',
        title: '庶务司',
        levelText: 'Lv.0 -> Lv.1',
        description: '提高待领取金币保留时长，减少忙碌玩家的静默损失。',
        effectText: '当前 待领取保留时长 0 小时，升级后 待领取保留时长 26 小时。',
        costText: '需要主城 Lv.8',
        action: { label: '查看条件', target: 'building', tone: 'ghost' },
        locked: true,
      },
    ],
  },
  army: {
    unitCostGold: 100,
    unitTrainingSeconds: 60,
    queue: null,
  },
  farm: {
    hero: {
      eyebrow: '田地经营',
      title: '丰熟 1 块 · 成熟中 2 块',
      description: '农场以田地为主，点击空地即可继续播种，进入丰熟后直接收取。',
      action: { label: '开始培育', target: 'farm', tone: 'primary' },
    },
    fields: [
      {
        id: 'field-1',
        code: '田地 01',
        title: '丰熟期',
        badge: '丰熟',
        cropName: '青灵麦',
        tone: 'mature',
        progressRemainingSeconds: 0,
        progressTotalSeconds: 1,
        yieldGold: 1260,
        description: '点击收取，触发爆金币并结算本轮成熟收益。',
        actions: [
          { label: '成熟收取', target: 'farm', tone: 'primary' },
        ],
      },
      {
        id: 'field-2',
        code: '田地 02',
        title: '播种期',
        badge: '播种',
        cropName: '青灵麦',
        tone: 'seeded',
        progressRemainingSeconds: 2535,
        progressTotalSeconds: 3600,
        yieldGold: 420,
        description: '播种刚完成，等待进入成长后再决定是否抢收。',
        actions: [],
      },
      {
        id: 'field-3',
        code: '田地 03',
        title: '成熟期',
        badge: '成熟',
        cropName: '青灵麦',
        tone: 'growing',
        progressRemainingSeconds: 4690,
        progressTotalSeconds: 7200,
        yieldGold: 660,
        description: '可抢收，点击后直接结算一轮提前收取结果。',
        actions: [
          { label: '提前收取', target: 'farm', tone: 'secondary' },
        ],
      },
      {
        id: 'field-4',
        code: '田地 04',
        title: '未解锁',
        badge: '待解锁',
        cropName: undefined,
        tone: 'locked',
        progressRemainingSeconds: 0,
        progressTotalSeconds: 1,
        yieldGold: 0,
        description: '主城Lv.15 自动解锁',
        actions: [],
      },
    ],
    guide: {
      title: '农场线引导',
      description: '以后如果农场增加培育品类、天气、地块事件和成熟策略，都可以继续在这个页面扩展。',
      actions: [
        { label: '打开主城页', target: 'building', tone: 'secondary' },
        { label: '返回首页', target: 'home', tone: 'ghost' },
      ],
    },
  },
  raid: {
    hero: {
      eyebrow: '可掠夺目标',
      title: '剩余免费掠夺 2 / 3',
      description: '进入页面后先看目标列表，重点判断等级、阵营和当前值不值得出手。',
      action: { label: '刷新目标', target: 'raid', tone: 'secondary' },
    },
    targets: [
      {
        id: 'target-1',
        name: '烬牙',
        faction: '魔界',
        level: 5,
        combatPower: '1,320',
        summary: '魔界 · 资源高 · 防守偏弱',
        loot: '420~560 金币',
        risk: '高风险',
        detail: '成熟田 2 块 · 可掠 520 · 今日被掠 1 次',
        action: { label: '发起掠夺', target: 'raid', tone: 'primary' },
      },
      {
        id: 'target-2',
        name: '云栖',
        faction: '仙界',
        level: 4,
        combatPower: '1,080',
        summary: '仙界 · 资源中 · 减损明显',
        loot: '260~340 金币',
        risk: '中风险',
        detail: '成熟田 1 块 · 可掠 260 · 防守偏稳',
        action: { label: '发起掠夺', target: 'raid', tone: 'secondary' },
      },
      {
        id: 'target-3',
        name: '临风',
        faction: '人界',
        level: 4,
        combatPower: '920',
        summary: '人界 · 资源低 · 风险较稳',
        loot: '180~260 金币',
        risk: '低风险',
        detail: '成长期 1 块 · 可掠 180 · 适合保守出手',
        action: { label: '发起掠夺', target: 'raid', tone: 'secondary' },
      },
      {
        id: 'target-4',
        name: '玄潮',
        faction: '魔界',
        level: 5,
        combatPower: '1,240',
        summary: '魔界 · 主宠等级高 · 默认仅见品种',
        loot: '360~480 金币',
        risk: '中高风险',
        detail: '成熟田 1 块 · 可掠 460 · 守田灵宠分散',
        action: { label: '发起掠夺', target: 'raid', tone: 'secondary' },
      },
      {
        id: 'target-5',
        name: '青槐',
        faction: '仙界',
        level: 3,
        combatPower: '760',
        summary: '仙界 · 主宠等级低 · 适合试探',
        loot: '150~220 金币',
        risk: '低风险',
        detail: '成熟田 1 块 · 可掠 140 · 防守偏弱',
        action: { label: '发起掠夺', target: 'raid', tone: 'secondary' },
      },
    ],
    detail: {
      advice: '默认先看等级和品种，若要决定是否越级，建议先做深度窥视。',
      actions: [
        { label: '调整灵宠', target: 'raid', tone: 'ghost' },
        { label: '确认派遣', target: 'raid', tone: 'primary' },
      ],
    },
    messageTemplates: mockRaidMessageTemplates,
  },
  report: {
    defense: [
      {
        title: '魔界 · 烬牙',
        tag: '小败 · 惜败而退',
        tone: 'danger',
        createdAt: new Date(Date.now() - 37 * 60 * 1000).toISOString(),
        unread: true,
        revengeable: true,
        summary: '37 分钟前对手以小胜拿走你 240 金币，并让你的主战灵宠进入明显损血状态。',
        actions: [
          { label: '查看详情', target: 'report', tone: 'ghost' },
          { label: '复仇', target: 'raid', tone: 'primary' },
        ],
      },
    ],
    attack: [
      {
        title: '匿名目标 · 赤砂营地',
        tag: '小胜 · 险取一筹',
        tone: 'success',
        createdAt: new Date(Date.now() - 58 * 60 * 1000).toISOString(),
        summary: '08:40 你以小胜拿到 436 金币、1 颗种子和 6 颗兽魂，主战灵宠扣血 18%。',
        actions: [{ label: '查看详情', target: 'report', tone: 'ghost' }],
      },
      {
        title: '匿名目标 · 玄潮',
        tag: '大胜 · 势如破竹',
        tone: 'success',
        createdAt: new Date(Date.now() - 132 * 60 * 1000).toISOString(),
        summary: '07:06 你以大胜拿到 512 金币、2 颗种子和 8 颗兽魂，主战灵宠仅扣血 11%。',
        actions: [{ label: '查看详情', target: 'report', tone: 'ghost' }],
      },
      {
        title: '匿名目标 · 云栖',
        tag: '相持 · 平分秋色',
        tone: 'neutral',
        createdAt: new Date(Date.now() - 205 * 60 * 1000).toISOString(),
        summary: '05:53 双方灵宠势均力敌，你只拿到少量金币与 3 颗兽魂，主战灵宠扣血 23%。',
        actions: [{ label: '查看详情', target: 'report', tone: 'ghost' }],
      },
    ],
    actions: [],
  },
  faction: {
    hero: {
      eyebrow: '阵营面板',
      title: '人界阵营',
      description: '当前每小时分红 20，先上缴再领取会更划算。',
      advantage: '人界优势：更擅长把上缴资源转成贡献与分红，适合平衡运营。',
      breakdown: '金额构成：基础分红 8/小时 + 贡献加成 12/小时',
      action: { label: '领取分红', target: 'faction', tone: 'primary' },
    },
    contribution: {
      title: '当前贡献值',
      value: '40',
      description: '100 金币 = 1 贡献，捐献后会立刻反馈到贡献值与分红构成。',
    },
    comparison: [
      { faction: '人界', advantage: '贡献转化更稳，适合分红运营。', gold: '82,400', power: '1,260', isCurrent: true },
      { faction: '仙界', advantage: '被掠损失减少 10%，更适合稳守。', gold: '79,600', power: '1,180' },
      { faction: '魔界', advantage: '掠夺收益增加 10%，但战损更高。', gold: '85,300', power: '1,340' },
    ],
    donate: {
      title: '捐献金币',
      description: '100 金币 = 1 贡献，确认后会立即从当前总金币扣除。',
      goldStep: 100,
      contributionRule: '100 金币 = 1 贡献。',
    },
    rankings: [
      { label: '1. 烬牙', value: '86', note: '魔界' },
      { label: '2. 玄潮', value: '72', note: '魔界' },
      { label: '3. 云栖', value: '65', note: '仙界' },
      { label: '4. 你', value: '40', note: '人界' },
    ],
  },
};

export const mockRaidTargetDetails: Record<string, ClientRaidTargetDetailResponse> = {
  'target-1': {
    app: APP_NAME,
    targetId: 'target-1',
    name: '烬牙',
    faction: '魔界',
    level: 5,
    combatPower: '1,320',
    fieldPreviewTone: 'mature',
    fieldStatus: '成熟田 2 块，成长期 1 块',
    fields: [
      createRaidDetailField({ id: 'target-1-field-1', code: '田地 01', title: '丰熟期', badge: '丰熟', tone: 'mature', description: '预计可收 420 金币' }),
      createRaidDetailField({ id: 'target-1-field-2', code: '田地 02', title: '丰熟期', badge: '丰熟', tone: 'mature', description: '预计可收 460 金币' }),
      createRaidDetailField({ id: 'target-1-field-3', code: '田地 03', title: '成熟期', badge: '成长', tone: 'growing', progressRemainingSeconds: 1860, progressTotalSeconds: 3600, description: '距离丰熟约半小时' }),
    ],
    raidableGold: '520 金币',
    exposedFruit: '2 块成熟田 · 预计 880 金币',
    raidRule: '按当前金币的一部分结算，本次预计命中 520 金币',
    defenseStatus: '防守偏弱，守田灵宠少于常见同级目标',
    protectionStatus: '当前无保护，可直接发起掠夺或通缉令',
    targetFarmBoardMessage: '成熟田可看，手快者得。',
    detail: '对手昵称烬牙，刚结束一轮农场收取，外露收益仍然较高。魔界加成偏向进攻，适合快速出手。',
    actions: [
      { label: '发起掠夺', target: 'raid', tone: 'primary' },
      { label: '发布通缉令', target: 'raid', tone: 'secondary' },
      { label: '邀请摇人', target: 'raid', tone: 'ghost' },
    ],
  },
  'target-2': {
    app: APP_NAME,
    targetId: 'target-2',
    name: '云栖',
    faction: '仙界',
    level: 4,
    combatPower: '1,080',
    fieldPreviewTone: 'seeded',
    fieldStatus: '成熟田 1 块，播种田 2 块',
    fields: [
      createRaidDetailField({ id: 'target-2-field-1', code: '田地 01', title: '丰熟期', badge: '丰熟', tone: 'mature', description: '预计可收 420 金币' }),
      createRaidDetailField({ id: 'target-2-field-2', code: '田地 02', title: '播种期', badge: '播种', tone: 'seeded', progressRemainingSeconds: 2280, progressTotalSeconds: 3600, description: '刚播下青灵麦，尚未进入成长' }),
      createRaidDetailField({ id: 'target-2-field-3', code: '田地 03', title: '播种期', badge: '播种', tone: 'seeded', progressRemainingSeconds: 3120, progressTotalSeconds: 3600, description: '新一轮播种刚开始' }),
    ],
    raidableGold: '260 金币',
    exposedFruit: '1 块成熟田 · 预计 420 金币',
    raidRule: '按当前金币的一部分结算，本次预计命中 260 金币',
    defenseStatus: '防守偏稳，仙界被掠损失减免明显',
    protectionStatus: '刚结束保护期，可被单人试探',
    targetFarmBoardMessage: '仙田清静，来者留名。',
    detail: '对手昵称云栖，收益中等但仙界自带减损，适合先做一轮稳妥试探。',
    actions: [
      { label: '发起掠夺', target: 'raid', tone: 'primary' },
      { label: '发布通缉令', target: 'raid', tone: 'secondary' },
      { label: '邀请摇人', target: 'raid', tone: 'ghost' },
    ],
  },
  'target-3': {
    app: APP_NAME,
    targetId: 'target-3',
    name: '临风',
    faction: '人界',
    level: 4,
    combatPower: '920',
    fieldPreviewTone: 'growing',
    fieldStatus: '成长期 1 块，空闲田 1 块',
    fields: [
      createRaidDetailField({ id: 'target-3-field-1', code: '田地 01', title: '成熟期', badge: '成长', tone: 'growing', progressRemainingSeconds: 1440, progressTotalSeconds: 3600, description: '成长尾段，快要进入丰熟' }),
      createRaidDetailField({ id: 'target-3-field-2', code: '田地 02', title: '空闲期', badge: '空闲', tone: 'empty', description: '当前未播种，暂无外露收益' }),
    ],
    raidableGold: '180 金币',
    exposedFruit: '1 块成长尾段田 · 预计 260 金币',
    raidRule: '按当前金币的一部分结算，本次预计命中 180 金币',
    defenseStatus: '人界经营向，防守一般，但暴露收益偏低',
    protectionStatus: '今日未被掠，可正常查看并试探',
    targetFarmBoardMessage: '小田薄收，路过随缘。',
    detail: '对手昵称临风，收益较低，更适合作为保守出手对象。',
    actions: [
      { label: '发起掠夺', target: 'raid', tone: 'primary' },
      { label: '发布通缉令', target: 'raid', tone: 'secondary' },
      { label: '邀请摇人', target: 'raid', tone: 'ghost' },
    ],
  },
  'target-4': {
    app: APP_NAME,
    targetId: 'target-4',
    name: '玄潮',
    faction: '魔界',
    level: 5,
    combatPower: '1,240',
    fieldPreviewTone: 'mature',
    fieldStatus: '成熟田 1 块，成长期 2 块',
    fields: [
      createRaidDetailField({ id: 'target-4-field-1', code: '田地 01', title: '丰熟期', badge: '丰熟', tone: 'mature', description: '预计可收 510 金币' }),
      createRaidDetailField({ id: 'target-4-field-2', code: '田地 02', title: '成熟期', badge: '成长', tone: 'growing', progressRemainingSeconds: 2640, progressTotalSeconds: 7200, description: '收益尚未完全外露' }),
      createRaidDetailField({ id: 'target-4-field-3', code: '田地 03', title: '成熟期', badge: '成长', tone: 'growing', progressRemainingSeconds: 4980, progressTotalSeconds: 7200, description: '还在中段成长' }),
    ],
    raidableGold: '460 金币',
    exposedFruit: '1 块成熟田 · 预计 510 金币',
    raidRule: '按当前金币的一部分结算，本次预计命中 460 金币',
    defenseStatus: '中等防守，守备偏强但守田灵宠分散',
    protectionStatus: '当前无保护，可立即出手',
    targetFarmBoardMessage: '守田不易，量力而行。',
    detail: '对手昵称玄潮，主城等级高一档，收益不错，但正面强碰战损会更高。',
    actions: [
      { label: '发起掠夺', target: 'raid', tone: 'primary' },
      { label: '发布通缉令', target: 'raid', tone: 'secondary' },
      { label: '邀请摇人', target: 'raid', tone: 'ghost' },
    ],
  },
  'target-5': {
    app: APP_NAME,
    targetId: 'target-5',
    name: '青槐',
    faction: '仙界',
    level: 3,
    combatPower: '760',
    fieldPreviewTone: 'mature',
    fieldStatus: '成熟田 1 块，空闲田 2 块',
    fields: [
      createRaidDetailField({ id: 'target-5-field-1', code: '田地 01', title: '丰熟期', badge: '丰熟', tone: 'mature', description: '预计可收 190 金币' }),
      createRaidDetailField({ id: 'target-5-field-2', code: '田地 02', title: '空闲期', badge: '空闲', tone: 'empty', description: '暂未播种' }),
      createRaidDetailField({ id: 'target-5-field-3', code: '田地 03', title: '空闲期', badge: '空闲', tone: 'empty', description: '暂未播种' }),
    ],
    raidableGold: '140 金币',
    exposedFruit: '1 块成熟田 · 预计 190 金币',
    raidRule: '按当前金币的一部分结算，本次预计命中 140 金币',
    defenseStatus: '防守偏弱，适合低损验证',
    protectionStatus: '保护已结束，可正常掠夺',
    targetFarmBoardMessage: '新手田地，请轻些下手。',
    detail: '对手昵称青槐，适合低风险起手，重点看田地收益是否值得你消耗免费次数。',
    actions: [
      { label: '发起掠夺', target: 'raid', tone: 'primary' },
      { label: '发布通缉令', target: 'raid', tone: 'secondary' },
      { label: '邀请摇人', target: 'raid', tone: 'ghost' },
    ],
  },
};
