import { APP_NAME, type ClientBootstrapResponse, type ClientRaidTargetDetailResponse, type ClientSceneContentResponse, type HomeSummaryResponse } from '@trinitywar/shared';

export const mockBootstrap: ClientBootstrapResponse = {
  app: APP_NAME,
  env: 'local',
  version: '0.1.0',
  serverTime: new Date('2026-05-09T10:00:00+08:00').toISOString(),
  season: {
    seasonNumber: 3,
    currentWeek: 1,
    totalWeeks: 4,
  },
};

export const mockHomeSummary: HomeSummaryResponse = {
  app: APP_NAME,
  playerName: '人界领主·临川',
  factionName: '人界',
  castleLevel: 4,
  staminaStatus: '免费掠夺 2/3',
  fieldStatus: '成熟田地 1 块，成长中 1 块',
  reportStatus: '未读战报 2，免费复仇 1',
  resources: [
    { label: '我的金币', value: '4,280 / 5,000', tone: 'vault' },
  ],
  pendingClaims: [
    { source: 'tax', label: '主城税收', value: '380', description: '当前每小时产出 190 金币，领取后直接入库。' },
    { source: 'faction', label: '阵营分红', value: '540', description: '当前每小时可分到 200 金币，来自阵营结算与贡献加成。' },
  ],
  primaryActions: [
    { key: 'building', title: '建筑', description: '升级主城与金币容量' },
    { key: 'farm', title: '农场', description: '收成熟田地' },
    { key: 'raid', title: '掠夺', description: '查看可掠夺目标' },
    { key: 'report', title: '战报', description: '处理未读与复仇' },
    { key: 'faction', title: '阵营', description: '上缴并查看分红' },
  ],
};

export const mockSceneContent: ClientSceneContentResponse = {
  app: APP_NAME,
  building: {
    upgrades: [
      {
        id: 'castle',
        title: '主城升级',
        description: 'Lv.4 -> Lv.5，主城税收由每小时 190 提升到 260。',
        costText: '消耗 1,800 金币',
        action: { label: '升级主城', target: 'building', tone: 'primary' },
      },
      {
        id: 'vault',
        title: '金库升级',
        description: 'Lv.3 -> Lv.4，容量由 5,000 提升到 6,600。',
        costText: '消耗 1,150 金币',
        action: { label: '升级金库', target: 'building', tone: 'secondary' },
      },
      {
        id: 'field-slot',
        title: '田地位升级',
        description: 'Lv.1 -> Lv.2，新增第 2 个培育位。',
        costText: '消耗 980 金币',
        action: { label: '升级田地位', target: 'building', tone: 'secondary' },
      },
      {
        id: 'watchtower',
        title: '防守建筑升级',
        description: 'Lv.1 -> Lv.2，降低单次被掠比例并强化田地防守。',
        costText: '需要主城 Lv.5',
        locked: true,
        action: { label: '查看条件', target: 'building', tone: 'ghost' },
      },
    ],
  },
  farm: {
    hero: {
      eyebrow: '田地经营',
      title: '成熟 1 块 · 生长中 2 块',
      description: '农场以田地为主，点击空地即可继续播种，成熟后直接收取。',
      action: { label: '开始培育', target: 'farm', tone: 'primary' },
    },
    fields: [
      {
        id: 'field-1',
        code: '田地 01',
        title: '成熟期',
        badge: '成熟',
        tone: 'mature',
        progressRemainingSeconds: 0,
        progressTotalSeconds: 1,
        description: '收取金额 1,260 金币',
        actions: [
          { label: '成熟收取', target: 'farm', tone: 'primary' },
        ],
      },
      {
        id: 'field-2',
        code: '田地 02',
        title: '播种期',
        badge: '播种',
        tone: 'seeded',
        progressRemainingSeconds: 2535,
        progressTotalSeconds: 3600,
        description: '收取金额 520 金币',
        actions: [
          { label: '查看阶段', target: 'farm', tone: 'ghost' },
        ],
      },
      {
        id: 'field-3',
        code: '田地 03',
        title: '成长期',
        badge: '成长',
        tone: 'growing',
        progressRemainingSeconds: 4690,
        progressTotalSeconds: 7200,
        description: '收取金额 660 金币',
        actions: [
          { label: '提前收取', target: 'farm', tone: 'secondary' },
        ],
      },
      {
        id: 'field-4',
        code: '田地 04',
        title: '未解锁',
        badge: '待解锁',
        tone: 'locked',
        progressRemainingSeconds: 0,
        progressTotalSeconds: 1,
        description: '收取金额 0 金币',
        actions: [{ label: '解锁田地', target: 'farm', tone: 'secondary' }],
      },
    ],
    guide: {
      title: '农场线引导',
      description: '以后如果农场增加培育品类、天气、地块事件和成熟策略，都可以继续在这个页面扩展。',
      actions: [
        { label: '打开建筑页', target: 'building', tone: 'secondary' },
        { label: '返回主城', target: 'home', tone: 'ghost' },
      ],
    },
  },
  raid: {
    hero: {
      eyebrow: '可掠夺目标',
      title: '剩余免费掠夺 2 / 3',
      description: '进入页面后先看目标列表，重点判断等级、阵营和当前值不值得出手。',
      action: { label: '刷新目标', target: 'raid', tone: 'secondary' },
    },
    targets: [
      {
        id: 'target-1',
        name: '烬牙',
        faction: '魔界',
        level: 5,
        combatPower: '1,320',
        summary: '魔界 · 资源高 · 防守偏弱',
        loot: '420~560 金币',
        risk: '高风险',
        detail: '成熟田 2 块 · 可掠 520 · 今日被掠 1 次',
        action: { label: '发起掠夺', target: 'raid', tone: 'primary' },
      },
      {
        id: 'target-2',
        name: '云栖',
        faction: '仙界',
        level: 4,
        combatPower: '1,080',
        summary: '仙界 · 资源中 · 减损明显',
        loot: '260~340 金币',
        risk: '中风险',
        detail: '成熟田 1 块 · 可掠 260 · 防守偏稳',
        action: { label: '发起掠夺', target: 'raid', tone: 'secondary' },
      },
      {
        id: 'target-3',
        name: '临风',
        faction: '人界',
        level: 4,
        combatPower: '920',
        summary: '人界 · 资源低 · 风险较稳',
        loot: '180~260 金币',
        risk: '低风险',
        detail: '成长期 1 块 · 可掠 180 · 适合保守出手',
        action: { label: '发起掠夺', target: 'raid', tone: 'secondary' },
      },
      {
        id: 'target-4',
        name: '玄潮',
        faction: '魔界',
        level: 5,
        combatPower: '1,240',
        summary: '魔界 · 资源中高 · 战力偏高',
        loot: '360~480 金币',
        risk: '中高风险',
        detail: '成熟田 1 块 · 可掠 460 · 驻防分散',
        action: { label: '发起掠夺', target: 'raid', tone: 'secondary' },
      },
      {
        id: 'target-5',
        name: '青槐',
        faction: '仙界',
        level: 3,
        combatPower: '760',
        summary: '仙界 · 资源低 · 适合起手',
        loot: '150~220 金币',
        risk: '低风险',
        detail: '成熟田 1 块 · 可掠 140 · 防守偏弱',
        action: { label: '发起掠夺', target: 'raid', tone: 'secondary' },
      },
    ],
    detail: {
      advice: '出征建议：派出 90~110 掠夺兵',
      actions: [
        { label: '更换兵力', target: 'raid', tone: 'ghost' },
        { label: '确认出兵', target: 'raid', tone: 'primary' },
      ],
    },
  },
  report: {
    defense: [
      {
        title: '魔界 · 烬牙',
        tag: '可复仇',
        tone: 'danger',
        unread: true,
        revengeable: true,
        summary: '37 分钟前成功掠走你田地 240 金币，击伤 8 名守备兵。',
        actions: [
          { label: '查看详情', target: 'report', tone: 'ghost' },
          { label: '复仇', target: 'raid', tone: 'primary' },
        ],
      },
      {
        title: '系统结算',
        tag: '分红记录',
        tone: 'neutral',
        unread: true,
        summary: '10:00 阵营小时分红 +200，当前待领取分红 540。',
        actions: [{ label: '查看详情', target: 'faction', tone: 'ghost' }],
      },
    ],
    attack: [
      {
        title: '匿名目标 · 赤砂营地',
        tag: '掠夺成功',
        tone: 'success',
        summary: '08:40 你成功掠夺 436 金币，获得 18 点掠夺积分。',
        actions: [{ label: '查看详情', target: 'report', tone: 'ghost' }],
      },
    ],
    actions: [
      { label: '一键已读', target: 'report', tone: 'secondary' },
      { label: '返回主城', target: 'home', tone: 'primary' },
    ],
  },
  faction: {
    hero: {
      eyebrow: '人界阵营面板',
      title: '当前待领取分红 540',
      description: '当前每小时可分到 200 金币，其中基础分红 160，贡献加成 40。',
      action: { label: '领取分红', target: 'faction', tone: 'primary' },
    },
    overview: [
      { label: '阵营公库', value: '82,400' },
      { label: '当前每小时总分红', value: '200' },
      { label: '本小时基础分红', value: '160' },
      { label: '个人贡献加成', value: '+40' },
    ],
    donate: {
      title: '金币上缴',
      description: '上缴会立刻增加贡献值，当前你的每小时分红为 200，后续会随贡献变化继续浮动。',
      actions: [
        { label: '金币上缴', target: 'faction', tone: 'secondary' },
        { label: '查看说明', target: 'faction', tone: 'ghost' },
      ],
    },
    rankings: [
      { label: '1. 烬牙', value: '2,340' },
      { label: '2. 你', value: '2,120' },
      { label: '3. 玄潮', value: '1,980' },
    ],
  },
};

export const mockRaidTargetDetails: Record<string, ClientRaidTargetDetailResponse> = {
  'target-1': {
    app: APP_NAME,
    targetId: 'target-1',
    name: '烬牙',
    faction: '魔界',
    level: 5,
    combatPower: '1,320',
    fieldPreviewTone: 'mature',
    fieldStatus: '成熟田 2 块，成长期 1 块',
    raidableGold: '520 金币',
    exposedFruit: '2 块成熟田 · 预计 880 金币',
    raidRule: '按当前金币的一部分结算，本次预计命中 520 金币',
    defenseStatus: '防守偏弱，驻守兵少于常见同级目标',
    protectionStatus: '当前无保护，可直接发起掠夺或通缉令',
    detail: '对手昵称烬牙，刚结束一轮农场收取，外露收益仍然较高。魔界加成偏向进攻，适合快速出手。',
    actions: [
      { label: '发起掠夺', target: 'raid', tone: 'primary' },
      { label: '发布通缉令', target: 'raid', tone: 'secondary' },
      { label: '邀请摇人', target: 'raid', tone: 'ghost' },
      { label: '分享目标', target: 'raid', tone: 'ghost' },
    ],
  },
  'target-2': {
    app: APP_NAME,
    targetId: 'target-2',
    name: '云栖',
    faction: '仙界',
    level: 4,
    combatPower: '1,080',
    fieldPreviewTone: 'seeded',
    fieldStatus: '成熟田 1 块，播种田 2 块',
    raidableGold: '260 金币',
    exposedFruit: '1 块成熟田 · 预计 420 金币',
    raidRule: '按当前金币的一部分结算，本次预计命中 260 金币',
    defenseStatus: '防守偏稳，仙界被掠损失减免明显',
    protectionStatus: '刚结束保护期，可被单人试探',
    detail: '对手昵称云栖，收益中等但仙界自带减损，适合先做一轮稳妥试探。',
    actions: [
      { label: '发起掠夺', target: 'raid', tone: 'primary' },
      { label: '发布通缉令', target: 'raid', tone: 'secondary' },
      { label: '邀请摇人', target: 'raid', tone: 'ghost' },
      { label: '分享目标', target: 'raid', tone: 'ghost' },
    ],
  },
  'target-3': {
    app: APP_NAME,
    targetId: 'target-3',
    name: '临风',
    faction: '人界',
    level: 4,
    combatPower: '920',
    fieldPreviewTone: 'growing',
    fieldStatus: '成长期 1 块，空闲田 1 块',
    raidableGold: '180 金币',
    exposedFruit: '1 块成长尾段田 · 预计 260 金币',
    raidRule: '按当前金币的一部分结算，本次预计命中 180 金币',
    defenseStatus: '人界经营向，防守一般，但暴露收益偏低',
    protectionStatus: '今日未被掠，可正常查看并试探',
    detail: '对手昵称临风，收益较低，更适合作为保守出手对象。',
    actions: [
      { label: '发起掠夺', target: 'raid', tone: 'primary' },
      { label: '发布通缉令', target: 'raid', tone: 'secondary' },
      { label: '邀请摇人', target: 'raid', tone: 'ghost' },
      { label: '分享目标', target: 'raid', tone: 'ghost' },
    ],
  },
  'target-4': {
    app: APP_NAME,
    targetId: 'target-4',
    name: '玄潮',
    faction: '魔界',
    level: 5,
    combatPower: '1,240',
    fieldPreviewTone: 'mature',
    fieldStatus: '成熟田 1 块，成长期 2 块',
    raidableGold: '460 金币',
    exposedFruit: '1 块成熟田 · 预计 510 金币',
    raidRule: '按当前金币的一部分结算，本次预计命中 460 金币',
    defenseStatus: '中等防守，战力高但驻防分散',
    protectionStatus: '当前无保护，可立即出手',
    detail: '对手昵称玄潮，主城等级高一档，收益不错，但正面强碰战损会更高。',
    actions: [
      { label: '发起掠夺', target: 'raid', tone: 'primary' },
      { label: '发布通缉令', target: 'raid', tone: 'secondary' },
      { label: '邀请摇人', target: 'raid', tone: 'ghost' },
      { label: '分享目标', target: 'raid', tone: 'ghost' },
    ],
  },
  'target-5': {
    app: APP_NAME,
    targetId: 'target-5',
    name: '青槐',
    faction: '仙界',
    level: 3,
    combatPower: '760',
    fieldPreviewTone: 'mature',
    fieldStatus: '成熟田 1 块，空闲田 2 块',
    raidableGold: '140 金币',
    exposedFruit: '1 块成熟田 · 预计 190 金币',
    raidRule: '按当前金币的一部分结算，本次预计命中 140 金币',
    defenseStatus: '防守偏弱，适合低损验证',
    protectionStatus: '保护已结束，可正常掠夺',
    detail: '对手昵称青槐，适合低风险起手，重点看田地收益是否值得你消耗免费次数。',
    actions: [
      { label: '发起掠夺', target: 'raid', tone: 'primary' },
      { label: '发布通缉令', target: 'raid', tone: 'secondary' },
      { label: '邀请摇人', target: 'raid', tone: 'ghost' },
      { label: '分享目标', target: 'raid', tone: 'ghost' },
    ],
  },
};