INSERT INTO "seed_definition" (
  "id",
  "seed_id",
  "label",
  "rarity",
  "sort_order",
  "seed_seconds",
  "grow_seconds",
  "mature_seconds",
  "ripe_window_seconds",
  "base_yield_gold",
  "harvest_seed_return",
  "strategy_note",
  "lore",
  "created_at",
  "updated_at"
) VALUES (
  'seeddef_qilingya',
  'qilingya',
  '启灵芽',
  'common',
  1,
  5,
  5,
  10,
  1800,
  50,
  1,
  '新手教程种，十秒完成第一轮收获。',
  '只在开荒时授予的一枚灵芽，破土极快。',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT ("seed_id") DO UPDATE SET
  "label" = EXCLUDED."label",
  "rarity" = EXCLUDED."rarity",
  "sort_order" = EXCLUDED."sort_order",
  "seed_seconds" = EXCLUDED."seed_seconds",
  "grow_seconds" = EXCLUDED."grow_seconds",
  "mature_seconds" = EXCLUDED."mature_seconds",
  "ripe_window_seconds" = EXCLUDED."ripe_window_seconds",
  "base_yield_gold" = EXCLUDED."base_yield_gold",
  "harvest_seed_return" = EXCLUDED."harvest_seed_return",
  "strategy_note" = EXCLUDED."strategy_note",
  "lore" = EXCLUDED."lore",
  "updated_at" = CURRENT_TIMESTAMP;
